#foo = ['a', 'b', 'c']
#print(foo[3])      # will this result in an error?

answer = True
why = '''It will result in an index error, because index being called exceeds
      the curent indexes in the list'''

print(answer)
print(why)

